//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.1
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmsCenter {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class SmsCenterSetting : global::System.Configuration.ApplicationSettingsBase {
        
        private static SmsCenterSetting defaultInstance = ((SmsCenterSetting)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SmsCenterSetting())));
        
        public static SmsCenterSetting Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=SMSRTKDV; User ID=smscenter; Password=zaq12wsx")]
        public string ConnectionStringRelease {
            get {
                return ((string)(this["ConnectionStringRelease"]));
            }
            set {
                this["ConnectionStringRelease"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25")]
        public uint LimitTask {
            get {
                return ((uint)(this["LimitTask"]));
            }
            set {
                this["LimitTask"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=SMSRTKDV; User ID=smscenter_debug; Password=zaq12wsx")]
        public string ConnectionStringDebug {
            get {
                return ((string)(this["ConnectionStringDebug"]));
            }
            set {
                this["ConnectionStringDebug"] = value;
            }
        }
    }
}
